### ISSUE TITLE
Phone app crashes 100% of the time whenever a chair setting is changed

### ISSUE THREAD

**Issue by praftery** [SoftwareDefinedBuildings/PECS-chair#10]
The phone app crashes immediately after I make any change to the chair settings. The chair does respond to the changed setting however, and the phone app reliably restarts. I'm in f010.

**Comment by gtfierro** [comment]
Have you tried rebooting app, phone and chair?

**Comment by praftery** [comment]
Yes on all three counts - same outcome. Joyce has a similar issue with her chair.

**Comment by praftery** [comment]
Also, this problem disappears and is replaced by the one mentioned in #9 when the internet connection is disabled.

**Comment by gtfierro** [comment]
I changed something on the server. Let me know if the issue pesists

**Comment by gtfierro** [comment]
Also, if internet connection is disabled, there is no issue. That is expected behavior when the app has no connectivity, but the app should probably stop giving the error message after awhile. I won't be able to take care of this unless someone is willing to set up the Android environment and update all the phones.

**Comment by praftery** [comment]
That change seems to have resolved the issue for me anyway.

Phone: Google Nexus 5, Android 5.1.1
Chair: f010

**Comment by gtfierro** [comment]
I'm reopening this issue because I think it is related to #5. The problem all comes down to the buggy actuation code at https://github.com/SoftwareDefinedBuildings/PECS-chair/blob/master/app/PECS-chair/server/actuateServer.py#L101-L122

**Comment by j6kim** [comment]
Soaziag's, Yongchao's & my app stopped crashing.
