### ISSUE TITLE
Google Nexus 5 testing

### ISSUE THREAD

**Issue by praftery** [SoftwareDefinedBuildings/PECS-chair#11]
I installed the app on my phone as Fred would like to test the chair and did not have an LG phone spare.
Everything works as expected, same problem with app crashing as issue #10.

Phone: Google Nexus 5, Android 5.1.1
Chair: f010

**Comment by gtfierro** [comment]
We've had problems with porting the app to other Android phones due to differences in the BLE stack or something along those lines. @immesys would know more. This is probably the same issue

**Comment by praftery** [comment]
Problem resolved
