### ISSUE TITLE
The plotter not reporting the most recent data

### ISSUE THREAD

**Issue by j6kim** [SoftwareDefinedBuildings/PECS-chair#12]
I'm checking my chair usage (f014) on Sam's plotter. I noticed that the last data showing up on the plotter is from 1.5 hr ago. It's 2:20pm. The last data points are from 1pm. My phone is connected to Airbears2. Is there a reason for the delay in data reporting?

**Comment by gtfierro** [comment]
It's only 15 minutes because of DST. Does your chair have battery?

**Comment by j6kim** [comment]
both chair and phone have been powered whole day.

**Comment by gtfierro** [comment]
Try restarting everything. Anytime anything doesn't work, always try restarting everything.

**Comment by j6kim** [comment]
@gtfierro @samkumar99 
I see that my chair is reporting on your Deckard but doesn't show up on Sam's plotter. I restarted both the chair controller multiple times already...

**Comment by gtfierro** [comment]
Works for me http://shell.storm.pm/?adPdDujadHrA97ASe
