### ISSUE TITLE
EECS-PSK

### ISSUE THREAD

**Issue by OpenBASGuest** [SoftwareDefinedBuildings/PECS-chair#13]
I can't seem to connect to it--maybe just where I am located in the building, but it tries to obtain an IP address and seems to fail. Under the EECS-PSK network it says "Avoided poor Internet connection".

**Comment by gtfierro** [comment]
Is this still an issue? Have you tried the same login on a computer in the same location?

**Comment by j6kim** [comment]
We are using Airbears2 for this study.
