### ISSUE TITLE
Status: Chair is not responding to bluetooth

### ISSUE THREAD

**Issue by tpeffer** [SoftwareDefinedBuildings/PECS-chair#14]
This is the chair in my office, f008.

I've tried: charging the battery, restarting the phone, restarting the phone app, disconnecting/ reconnecting, unplugging/replugging that pair of black plugs.

Any other suggestions?

**Comment by samkumar** [comment]
You could try turning off the phone and turning it back on. Sometimes that helps.

**Comment by tpeffer** [comment]
Thanks, Sam. Yep, did that. Does it matter what order I do any of the above?

**Comment by gtfierro** [comment]
Checking in on this issue -- has it persisted?

**Comment by tpeffer** [comment]
yes

On Tue, Aug 11, 2015 at 2:54 PM, Gabe Fierro notifications@github.com
wrote:

> Checking in on this issue -- has it persisted?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SoftwareDefinedBuildings/PECS-chair/issues/14#issuecomment-130089754
> .

## 

Therese Peffer
Associate Director, CITRIS i4Energy
Program Director, Enabling Technologies
Chair, Behavior Energy and Climate Change conference 2015
California Institute for Energy & Environment
University of California
510-289-4278 (mobile)
http://www.i4Energy.org
http://uc-ciee.org/

**Comment by gtfierro** [comment]
Can you see the expected BLE MAC using a BLE scanner application? Has anyone tried reprogramming the chair?

**Comment by j6kim** [comment]
I reflashed her chair controller. It works now.

**Comment by gtfierro** [comment]
Great!
