### ISSUE TITLE
f01b not reporting data on Deckard & Sam's plotter

### ISSUE THREAD

**Issue by j6kim** [SoftwareDefinedBuildings/PECS-chair#15]
The phone is connected to Airbears2. I can open an web browser and search on google. The phone app & f01b are paired and it controls the chair heating & cooling settings. I don't see any data coming from the chair though (deckard & sam's plotter).

**Comment by gtfierro** [comment]
Looks like it is now? http://shell.storm.pm/?Jkmcb2cugKCBdouch
