### ISSUE TITLE
f019 chair data not updating

### ISSUE THREAD

**Issue by j6kim** [SoftwareDefinedBuildings/PECS-chair#17]
the chair data of f019 has been stuck for a month. I restarted the phone & reset chair multiple times. but none of that seems to trigger the data transfer.

**Comment by gtfierro** [comment]
Is the phone connected to the internet via a network that isn't CalVisitor?

**Comment by j6kim** [comment]
When I checked, the phone was connected to Airbears2. I can check again this afternoon.

**Comment by j6kim** [comment]
I checked the internet connection. connected to Airbears2. The chair is working fine. The data is still stuck at a month ago.

**Comment by gtfierro** [comment]
Does that chair still respond to the phone? There might be a corner case the code doesn't cover. Does a different phone work? If not, try reflashing the chair

**Comment by j6kim** [comment]
The chair responds to the phone. I can try another phone.

**Comment by samkumar** [comment]
I think this chair may be bricked (in that the flash module may be messed up, as we have seen before). Gabe, does that sound plausible to you?

**Comment by j6kim** [comment]
The chair is responding to the phone. The phone is connected to Airbears2. However, the data is not being transferred. I reflashed the chair. The data still seems to be stuck. I forgot to try another phone. I'll do that later today.

**Comment by gtfierro** [comment]
Have you been using the instructions [here](https://github.com/SoftwareDefinedBuildings/PECS-chair/wiki/Programming-A-Chair), including the `sload factoryinit` and `sload ping` part?

**Comment by j6kim** [comment]
I didn't do sload factoryinit and sload ping. I will try that later.

**Comment by gtfierro** [comment]
So if you didn't do that when programming, then they are probably bricked. It's a pretty length recovery process if I remember correctly, @immesys ?

**Comment by j6kim** [comment]
reflashed the chair following the instructions on github. the data is still stuck at a month ago.

**Comment by gtfierro** [comment]
This is almost certainly bricked. There's a somewhat lengthy fix we can describe to you later

**Comment by immesys** [comment]
Following up on this. @j6kim when you say you followed the instructions on github, did you perform the 

```
sload ping
sload factoryinit
```

procedure? If so, can you please tell me the output of 

```
sload gattr
```

If it hangs or does anything else strange (like printing "bored now" or "timeout") then please paste that in. These are symptoms of not initializing the flash properly.

**Comment by j6kim** [comment]
I did sload ping & sload factoryinit. I will try sload gattr tomorrow morning when I visit SDH.

**Comment by samkumar** [comment]
We managed to resolve this issue yesterday. The issue was that the serial number of the chair was set incorrectly, causing the data for this chair to be added to the streams corresponding to a different chair.

By the way, running the command "sload gattr" will display the serial number of a chair (among other things).
