### ISSUE TITLE
App doesn't work when chair is run off battery

### ISSUE THREAD

**Issue by yongchaozhai** [SoftwareDefinedBuildings/PECS-chair#2]
1. Chair indentifier - 'f00f'
2. I was trying to pair my chair with the LG phone
3. Chair - no response; phone - failed to find the chair
4. Plug in the chair, problem solved

For new users, this may cause confusion since we are using a smaller battery than before, which needs to be charged every 2-3 days. So this issue may happen every 2-3 days.

**Comment by gtfierro** [comment]
Can you please provide the following information?
- the chair identifier (4 alphanumeric digits from the back of the chair, e.g. 'f00b')
- description of what you are trying to do
- description of what the chair/phone did
- description of what you have tried so far

**Comment by j6kim** [comment]
Gabe, FYI, the chair battery was drained when Yongchao was trying to use the phone app.

**Comment by gtfierro** [comment]
That explains it! Let me know if there are further issues

**Comment by gtfierro** [comment]
For further reference, please add new comments rather than editing your prior comments. Having the full history of the conversation is important
