### ISSUE TITLE
f00f not showing up on the plotter

### ISSUE THREAD

**Issue by j6kim** [SoftwareDefinedBuildings/PECS-chair#3]
1) the chair identifier: f00f
2) can't find the matching chair on the plotter
3) chair was deployed yesterday afternoon and has been used since then

**Comment by gtfierro** [comment]
The chair is configured to show up in the plotter, so my guess is the plotter has not received data from the chair. Can you check that the phone is connected to a WiFi network that is not CalVisitor?

**Comment by j6kim** [comment]
Yongchao (the chair user) was logged into Airbears2 yesterday. He is not at his desk currently. When he returns to desk this afternoon, he will try using the chair.

**Comment by gtfierro** [comment]
The phone will load historical data once it is connected both to the chair and to a WiFi network

**Comment by gtfierro** [comment]
Is this still an issue?

**Comment by j6kim** [comment]
I still don't see it on the plotter. Yongchao is out of office today. I'll ask him to check his Internet connection tomorrow.

**Comment by j6kim** [comment]
The phone was connected to CalVisitor. We switched to Airbears2. Now I see the chair on the plotter.

**Comment by gtfierro** [comment]
Great! This should be one of the first things we check from now on if a chair is not reporting.
