### ISSUE TITLE
Chair heating strips not working

### ISSUE THREAD

**Issue by immesys** [SoftwareDefinedBuildings/PECS-chair#4]
I used remote actuation to set my chair (f006) to 100% heat, but it is not heating me up. It is 32F here and I could really do with a warm chair. Please fix.

**Comment by samkumar** [comment]
You mentioned you were using remote actuation. Does one of the two conditions apply:
1. The chair is connected via 15.4 (there is a border router nearby).
2. There is an Internet-connected phone connected to the chair via Bluetooth.

-Sam

**Comment by immesys** [comment]
No, the chair is not connected to 15.4, but there is a phone connected to it via bluethooth. I just tried again and I know the actuation is working because I can see it on the plotter, but I don't feel any warmer. I can ask someone to check the phone to see if the screen has changed, but I don't think that is relevant.

**Comment by samkumar** [comment]
If you can see it on the plotter then the chair is reporting that it's heater setting is on. What is the occupancy reported as?

-Sam

**Comment by immesys** [comment]
The occupancy is occupied because I left something propped on the chair.

**Comment by immesys** [comment]
Actually the fans aren't cooling me down either. Am I doing something wrong?

**Comment by immesys** [comment]
wontfix?

![howrude](https://cloud.githubusercontent.com/assets/4234131/8766536/cbc8caaa-2df0-11e5-9f66-06d54ce97c08.jpg)

**Comment by gtfierro** [comment]
:-1:

**Comment by immesys** [comment]
Even gabe's chair is not heating me up!! Please help (´・ω・`)

**Comment by samkumar** [comment]
Does the phone app say " Please check internet connection"? This may be a problem in server side code. Try restarting if. And if you can, look at the screen sessions to see what happened.

Alternatively, it may be an issue with the occupancy sensor (there may be something in the chair, but the occupancy sensor isn't reporting it). You should try testing for that as well.

-Sam

**Comment by immesys** [comment]
I think it's a timezone thing because I'm in South Africa. We'll see if the problem still persists when I get back.

**Comment by samkumar** [comment]
Does the chair work properly when directly controlled from a phone? I suspect the occupancy sensor in the chair isn't working. However I don't have a computer with me so I can't verify in the plotter that that is the case. It's very peculiar that the chair reports that the heaters are set to be on, but that they actually aren't. Especially since the same code is used to (1) determine the duty cycle of PWM for the heaters, once every second, and (2) get the current chair setting when reporting to the phone. A faulty occupancy sensor is the only thing I can think of. 

I honestly can't think of a place where I do any timezone-dependent stuff. I always use UTC for everything. Though I guess it's worth looking into.

-Sam

**Comment by immesys** [comment]
Ironically Gabe and I did find a timezone dependent path in the actuation, but that was not the problem here. I think I have worked out the problem. Thx

**Comment by samkumar** [comment]
What was the problem?

**Comment by immesys** [comment]
Too much thermal isolation

**Comment by immesys** [comment]
I have a feeling that this issue is now affecting @gtfierro as well...

**Comment by gtfierro** [comment]
Two words: Poe's law

---

But seriously? The chair I have in my office in Denmark isn't heating me up OR cooling me down. The chair app on my phone won't even connect to it and YES, before you ask, I did check that I have the latest version.

**Comment by immesys** [comment]
Is the phone connected to the internet?

**Comment by gtfierro** [comment]
The internet is connected to my phone, if that's what you mean

**Comment by immesys** [comment]
Is the chair having trouble connecting via USB? If so, it's probably a problem with Sam's bluetooth driver corrupting the data interchange manifest or overriding the priority matrix.

**Comment by gtfierro** [comment]
We have to keep this issue open until we beat http://bugs.mysql.com/bug.php?id=11472, assuming it's ever closed

**Comment by immesys** [comment]
you're right. This is probably a cascading foreign key trigger bug. Is Sam assigned?

**Comment by samkumar** [comment]
Is the issue that remote actuation won't work, or that the phone won't connect to the chair?

**Comment by gtfierro** [comment]
@samkumar99 sure

**Comment by immesys** [comment]
@gtfierro yes

**Comment by gtfierro** [comment]
OH okay I see what you mean. 

Feels obvious now...

**Comment by immesys** [comment]
Sam, is this fixed?

**Comment by immesys** [comment]
It's OK, I can just work around it
