### ISSUE TITLE
Phone Unable to Connect to Chair

### ISSUE THREAD

**Issue by caindiaz** [SoftwareDefinedBuildings/PECS-chair#7]
Chair f011

Attempted to turn on fan in the morning (worked yesterday afternoon).  Phone is unable to establish connection with chair.

ChairTalk status remains: "Initiated bluetooth connection.  Waiting for chair..."

Attempted to restart phone and restart bluetooth, but that did not resolve the issue.

**Comment by gtfierro** [comment]
Have you restarted the chair by un/re-plugging it?

**Comment by caindiaz** [comment]
Yes, but the chair is still unable to connect. The phone restarts its 
own bluetooth to attempt to reconnect, but still fails.

Cain Diaz
Financial Analysis Supervisor
University of California, Berkeley
Campus Shared Services
Budget and Finance - Team 9
390D Wurster Hall
Berkeley, CA 94720-1839
T: (510) 642-2931
F: (510) 643-5571
Hours: 7:30 am - 4:30 pm

**Comment by gtfierro** [comment]
Did you restart the chair, and then quit the application and try to reconnect? Have you verified that you are connecting to the correct chair?

What happens when you hit "reconnect to chair" from within the app, and then try toggling the sliders?

**Comment by caindiaz** [comment]
Yes, I quit the app in the phone after restarting the chair and tried 
reconnecting.  Phone just stays at "Initiated bluetooth connection.  
Waiting for chair..." with no change.  If I select "Find My Chair" in 
the menu, it searches but doesn't find the chair.

When I toggle the sliders, the app says "Status: Chair is not responding 
to bluetooth..."
- Cain

Cain Diaz
Financial Analysis Supervisor
University of California, Berkeley
Campus Shared Services
Budget and Finance - Team 9
390D Wurster Hall
Berkeley, CA 94720-1839
T: (510) 642-2931
F: (510) 643-5571
Hours: 7:30 am - 4:30 pm

**Comment by gtfierro** [comment]
Does the chair have battery power?

**Comment by caindiaz** [comment]
It does, clicking the button on the chair shows 3 lights.

Cain Diaz
Financial Analysis Supervisor
University of California, Berkeley
Campus Shared Services
Budget and Finance - Team 9
390D Wurster Hall
Berkeley, CA 94720-1839
T: (510) 642-2931
F: (510) 643-5571
Hours: 7:30 am - 4:30 pm

**Comment by gtfierro** [comment]
Been very busy lately, sorry for not following up. Has this issue persisted?

**Comment by caindiaz** [comment]
No, I reset the chair again and everything was fine after.  Good as 
new.  Thanks!
- Cain

Cain Diaz
Financial Analysis Supervisor
University of California, Berkeley
Campus Shared Services
Budget and Finance - Team 9
390D Wurster Hall
Berkeley, CA 94720-1839
T: (510) 642-2931
F: (510) 643-5571
Hours: 7:30 am - 4:30 pm
