### ISSUE TITLE
F01B bottom randonmly switches from heating to cooling

### ISSUE THREAD

**Issue by j6kim** [SoftwareDefinedBuildings/PECS-chair#8]
F01B was in use & the bottom was on heating mode. While in usage, the bottom fan randomly started on its own. This happened several times this morning. The phone app showed the setting switching from heating to cooling when this happened. The phone was connected to Airbears2.

**Comment by gtfierro** [comment]
Probably the same issue as #5. Let me know if the issue persists after today.
