### ISSUE TITLE
Phone app displays "Using actuation request from smap failed" repeatedly

### ISSUE THREAD

**Issue by praftery** [SoftwareDefinedBuildings/PECS-chair#9]
This message occurs every ~10seconds since I switched on the phone and sat down in the chair this morning (2015/07/29 8:50am). The phone app has also repeatedly crashed and restarted. I can still control the chair however.

**Comment by gtfierro** [comment]
Oh yeah, I thought this might happen. Give me 10 min

**Comment by gtfierro** [comment]
Should be fixed. Let me know if it still shows up

**Comment by praftery** [comment]
The message no longer occurs, however the phone app crashes immediately after I make any change to the chair seetings. The chair settings continue to operate however. I'm in f010.

**Comment by gtfierro** [comment]
Can you file a separate issue? Try rebooting both the chair and the app first.
